class PythonLikelihood:
    def function(self, x: float) -> float: ...
    def function_vec(self, x: list[float]) -> list[float]: ...


class PythonModel:
    def integral(self) -> float: ...

class PythonPrior:
    def integral(self) -> float: ...

